### ISSUE TITLE
SSO Button Configuration

### ISSUE THREAD

**Issue by creppyfm** [creppyfm/DeleGate#55]
Need to match Google and GitHub sso buttons to redirect to OAuth2 authorization endpoints:

/login/oauth2/authorization/google
/login/oauth2/authorization/github

**Comment by kensonjohnson** [comment]
POST routes have changed to /oauth/google and /oauth/github

**Comment by kensonjohnson** [comment]
Both GET and POST routes have been changed to /auth/github and /auth/google
